### PR TITLE
Added favicon with attribution

### PR DESCRIPTION
**Pull request by parthpanchal123**
With this PR, new favicon image is added as seen in the below image and the Readme has an attribution for it as well .

image

### CODE REVIEW

**Review by gouravkhunger — APPROVED** [review]

**Comment by gouravkhunger** [comment]
Thanks a lot for the PR!

**Comment by parthpanchal123** [comment]
Sorry to bother but can you tell me what have you used to display the app preview frame in the readme Or is it original screenshot?

**Comment by gouravkhunger** [comment]
It is the original screenshot that I took. macOS has an inbuilt feature to take screenshots of a single app window :)

If you wish for something minimal, you can use some website like https://screen.guru to get a cool screenshot of a website.

**Comment by parthpanchal123** [comment]
Can you contribute screenshots for my project [Antariksh](https://antariksh.vercel.app/) if you have time ? I tried other sites but they don't look that good .

 [Github repo](https://github.com/parthpanchal123/antariksh)

**Comment by gouravkhunger** [comment]
Sure, will do that by tonight :)
Right now I am a bit busy 😅

**Pull request merged**
