### PR TITLE
add custom description

### LINKED ISSUE #12: Add optional custom description
Add custom description to make a specific message from users

### PR DESCRIPTION
**Pull request by Alitindrawan24**
Adding a form to input custom description from user but optional, if empty the description still random from the app
fix #12

### CODE REVIEW

**Review by gouravkhunger — COMMENTED** [review]
Hi, thanks a lot for the PR! But consider this: If someone adds a long message, the base 60 string will make the URL too long, and if they share that URL with the person they want to wish, this would look spammy.

As for now, I don't want to mess up anything with the `hbdwish.ml/<name>` URL scheme, if you wish to contribute anything other than URL changes, or things that would require API/Database, I would really appreciate it. I am closing this PR for now. Thanks a lot for understanding!

**Comment by Alitindrawan24** [comment]
Ahh okay I see, so I think I cant do anything improvement with a dynamic message without modifying the URL scheme except using Database. But using a database will need complex changes

**Comment by gouravkhunger** [comment]
Exactly :)

**Comment by Alitindrawan24** [comment]
I am sorry can't give a contribution because my idea maybe breaks the simplicity of the web. But anyway this project is very good :)

**Comment by gouravkhunger** [comment]
No worries at all! If you think you can add something that will not break the URL scheme, or something as the [different colour scheme](https://github.com/gouravkhunger/nextjs-birthday-wish/pull/11) PR, which would make a good impact even with a URL change, that would be better.

I allowed URL change over there because it is just to add a single integer for color implementation, but in this case, the URL string would become dynamic, and can be huge if the description is very long!

If you have any such ideas or things you would want to see in the project, you are welcome to open an issue :)
And thanks for the complement =)

**Pull request closed without merging**
