### PR TITLE
Copy link button with color change, useState code changes.

### PR DESCRIPTION
**Pull request by chaitanyks**
Copy link button with color change, useState code changes.

### CODE REVIEW

**Review by gouravkhunger — CHANGES_REQUESTED** [review]
Thanks a lot for this feature!

I would like to see a few more changes before it gets merged:

- Probably implement something like: If a user creates a birthday wish from the home page, the copy link should be visible, else if a person comes from a URL, the it shouldn't be shown. You might need to pass data from the home page to the name page, if that data exists you can show the button else hide it.

- The copy button should not be aligned horizontally with the back button which says "Create a wish", it should be in a vertical orientation, above the create a wish button.

- Make the link copied button have the color `#10B981` as it would be consistent with another feature being implemented in the project.

- Also, the shadow needs to be fixed :)
image

Looking forward to these changes. Once they are done, I would happily merge them. Thanks a lot for your contribution :)

**Comment by chaitanyks** [comment]
okay, I will do the changes.

**Comment by gouravkhunger** [comment]
Amazing :)

**Comment by chaitanyks** [comment]
The below point will take more code changes:

1. Probably implement something like: If a user creates a birthday wish from the home page, the copy link should be visible, else if a person comes from a URL, it shouldn't be shown. You might need to pass data from the home page to the name page, if that data exists you can show the button else hide it.

I have created the buttonVisible condition it will sync with route props in upcoming code changes and I have completed the rest of the changes.

**Comment by gouravkhunger** [comment]
Woah that is really a great improvement! Thanks mate :)

Now the left thing is:
- Hide the copy button if the user comes directly from the url, and show when he comes from the home page, i.e., if he himself creates a link.
- Also, just a simple copy paste, can you move the copy button above the create a wish button 😅. That would be a better hierarchy :)

Again, thanks for this amazing contribution. Appreciated!

**Comment by chaitanyks** [comment]
Fixed.

**Comment by chaitanyks** [comment]
Hide the copy button if the user comes directly from the url, and show when he comes from the home page, i.e., if he himself creates a link.
That point will take code to refactor because you are using generic [name].js route, It will not accept any props.

**Comment by chaitanyks** [comment]
My suggestion: Create a new Issue for that point.

**Comment by chaitanyks** [comment]
The scope of the issue "Adding a copy link button" has been completed.

**Comment by adarshzpatel** [comment]
I think a better  & simple solution would be to show the link on the homepage and the user can copy the link from the homepage itself.

Instead of  redirecting after submit we can show the link and copy button.

**Comment by gouravkhunger** [comment]
Okay I found a better approach, when the user presses the "Go" button, copy the link at that time. This would be a lot better, why didn't it strike my mind before xD.

I am really sorry that your effort didn't get a reward. Really sorry for you :(

**Pull request closed without merging**
