### PR TITLE
implemented multiple theme suppport

### PR DESCRIPTION
**Pull request by adarshzpatel**

### CODE REVIEW

**Comment by gouravkhunger** [comment]
Hi @adarshzpatel 
This is something next level. I didn't expect that this repo would get these next-level contributions. Thanks a lot!

But there is just 1 issue, can you please go through it:
Consider this scenario, someone creates a birthday wish and then shares the URL to send to them. Now, the default color is blue, and there is no way one can define the color without changing any parameter in the URL.

I would love to see something like this: The URL scheme can be changed for betterment in this scenario, right now it is `hbdwish.ml/<name>`. Can you do something like `hbdwish.ml/<name>/<color-int>` where `color-int` is the integer that defines the color that the theme should use.

Color indexes:
none for Blue, just the URL `hbdwish.ml/<name>` should mean blue colour
1 for green, `hbdwish.ml/<name>/2` means green theme
similarly,
2 for purple
3 for yellow
and 4 for red.

Thanks once again! Really appreciated

**Comment by gouravkhunger** [comment]
Also, on the home page, by default, there is no shadow over the blue circle. It would be nice if it has the shadow by default :)

**Comment by adarshzpatel** [comment]
Yeah thanks for pointing it out . I forgot to take it into consideration that the  color would be reset when shared.

I will work on the url solution that you have suggested.

**Comment by gouravkhunger** [comment]
Amazing!

**Comment by adarshzpatel** [comment]
Implemented what you said , now you can use themes from url itself and the GO button changes to url if the theme is changed.

**Comment by gouravkhunger** [comment]
This looks great, but I was thinking if it could be changed from `hbdwish.ml/<name>?colour=<number>` to just `hbdwish.ml/<name>/<number>`

Is that possible? If yes that would look more professional and better!

**Comment by adarshzpatel** [comment]
Hey @gouravkhunger I looked into the official Next.js [documentation](https://nextjs.org/docs/routing/dynamic-routes) and found a solution and implemented it .

Major Changes : -
1. Changed [name].js to [...name].js to catch multiple routes
2. Now name variable is an array which has 'name' in its 0th index and color id in 1st Index.

**Comment by gouravkhunger** [comment]
Thanks a lot, this was a really great feature!! Really really appreciated :)

**Comment by adarshzpatel** [comment]
No problem , this was a great learning experience for me as well ,before this I didn't know much next.js routing & theming but now small project of yours helped me to learn as well implement it .

**Comment by gouravkhunger** [comment]
Amazing! Even I am surprised that a small project of mine gained enough traction and now its becoming a really cool app. Happy to work with you :)

**Pull request merged**
